In [2]:
import numpy as np
import random
import math
import pandas as pd

In [3]:
dataSet = np.genfromtxt('x06simple.csv', delimiter = ',')

In [5]:
dataSet = dataSet[1:,1:]

In [14]:
print(dataSet.shape)

(44, 3)


In [8]:
random.seed(0)

In [9]:
np.random.shuffle(dataSet)

In [11]:
# finding the number of samples to be used in the training set

trainingSamples = int(len(dataSet) * 2/3)

In [12]:
print(trainingSamples)

29


In [30]:
training_data_x = dataSet[:trainingSamples, :-1]

In [71]:
training_data_y = dataSet[:trainingSamples,-1]

training_data_y = np.reshape(training_data_y, (len(training_data_y), 1))

In [72]:
testing_data_x = dataSet[trainingSamples:, :-1]

In [73]:
testing_data_y = dataSet[trainingSamples:, -1]

testing_data_y = np.reshape(testing_data_y, (len(testing_data_y), 1))

In [74]:
# standardizing the training data

average_training_x = np.mean(training_data_x, axis=0)
std_training_x = np.std(training_data_x, axis=0)

training_x = (training_data_x - average_training_x) / std_training_x

In [75]:
# standardizing the testing data

average_testing_x = np.mean(testing_data_x, axis=0)
std_testing_x = np.std(testing_data_x, axis=0)

testing_x = (testing_data_x - average_testing_x) / std_testing_x

In [76]:
print(training_x.shape)

(29, 2)


In [77]:
print (testing_x.shape)

(15, 2)


In [79]:
training_ones = np.ones((len(training_x)))

training_ones = np.reshape(training_ones, (len(training_ones), 1))

In [80]:
x = np.column_stack((training_ones, training_x))

In [82]:
testing_ones = np.ones((len(testing_x)))

testing_ones = np.reshape(testing_ones, (len(testing_ones), 1))

In [83]:
x_testing = np.column_stack((testing_ones, testing_x))

In [84]:
print(x_testing.shape)

(15, 3)


In [85]:
# computing weights

xtx = np.dot(np.transpose(x), x)

In [86]:
xtx_inv = np.linalg.inv(xtx)

In [87]:
print(xtx_inv)

[[ 3.44827586e-02 -2.52501219e-18 -1.51851128e-17]
 [-2.52501219e-18  3.53358545e-02 -5.49043444e-03]
 [-1.51851128e-17 -5.49043444e-03  3.53358545e-02]]


In [88]:
weights = np.dot ( np.dot(xtx_inv, np.transpose(x)), training_data_y)

In [89]:
print(weights)

[[3041.03448276]
 [1204.92155776]
 [-151.51005322]]


In [90]:
print(x_testing)

[[ 1.          1.30957712 -1.71679015]
 [ 1.          0.6053231  -0.79708114]
 [ 1.         -1.83441405  1.04233688]
 [ 1.          0.6053231   0.12262787]
 [ 1.          1.30957712 -0.79708114]
 [ 1.         -0.80318494  1.04233688]
 [ 1.          1.30957712  1.04233688]
 [ 1.         -1.48228704  0.12262787]
 [ 1.          0.25319609  1.04233688]
 [ 1.         -0.09893092 -0.79708114]
 [ 1.         -1.48228704  1.04233688]
 [ 1.         -0.45105793  0.12262787]
 [ 1.          0.25319609 -0.79708114]
 [ 1.          0.6053231   1.04233688]
 [ 1.         -0.09893092 -1.71679015]]


In [93]:
predicted_outputs = np.matmul(x_testing, weights)


In [92]:
print(testing_data_y)

[[4570.]
 [4495.]
 [ 590.]
 [4520.]
 [4600.]
 [2140.]
 [3257.]
 [1305.]
 [3030.]
 [4015.]
 [1205.]
 [3920.]
 [4315.]
 [3040.]
 [3535.]]


In [94]:
predicted_outputs - testing_data_y

array([[  309.08315633],
       [ -603.83285829],
       [   82.78493387],
       [ -768.17801922],
       [  139.73799539],
       [ -224.66488753],
       [ 1204.04767352],
       [  -68.58447836],
       [  158.191393  ],
       [ -972.40371197],
       [ -107.92963929],
       [-1441.03429975],
       [ -848.11828513],
       [  572.47681984],
       [ -353.05855104]])

In [97]:
out_2 = np.square(predicted_outputs - testing_data_y)

In [98]:
np.mean(out_2, axis =0)

array([454135.98759004])

In [99]:
np.sqrt(np.mean(out_2, axis =0))

array([673.89612522])