### Jared Balakrishnan
### CS383: Machine Learning
### Dr.Matt Burlick
### February 12, 2019


In [108]:
import numpy as np
import pandas as pd
import cv2
import random
import math

In [109]:
# reading in the input csv file into a numpy array
dataSet = np.genfromtxt('x06Simple.csv', delimiter = ',')

In [110]:
# ignoring the first column (indices) and the first row (column names)
requiredData = dataSet[1:, 1:]

In [111]:
print(requiredData.shape)

(44, 3)


In [112]:
print(requiredData)

[[  14.   25.  620.]
 [  28.   25. 1315.]
 [  41.   25. 2120.]
 [  55.   25. 2600.]
 [  69.   25. 3110.]
 [  83.   25. 3535.]
 [  97.   25. 3935.]
 [ 111.   25. 4465.]
 [ 125.   25. 4530.]
 [ 139.   25. 4570.]
 [ 153.   25. 4600.]
 [  14.   27.  625.]
 [  28.   27. 1215.]
 [  41.   27. 2110.]
 [  55.   27. 2805.]
 [  69.   27. 3255.]
 [  83.   27. 4015.]
 [  97.   27. 4315.]
 [ 111.   27. 4495.]
 [ 125.   27. 4535.]
 [ 139.   27. 4600.]
 [ 153.   27. 4600.]
 [  14.   29.  590.]
 [  28.   29. 1305.]
 [  41.   29. 2140.]
 [  55.   29. 2890.]
 [  69.   29. 3920.]
 [  83.   29. 3920.]
 [  97.   29. 4515.]
 [ 111.   29. 4520.]
 [ 125.   29. 4525.]
 [ 139.   29. 4565.]
 [ 153.   29. 4566.]
 [  14.   31.  590.]
 [  28.   31. 1205.]
 [  41.   31. 1915.]
 [  55.   31. 2140.]
 [  69.   31. 2710.]
 [  83.   31. 3020.]
 [  97.   31. 3030.]
 [ 111.   31. 3040.]
 [ 125.   31. 3180.]
 [ 139.   31. 3257.]
 [ 153.   31. 3214.]]


In [113]:
np.random.shuffle(requiredData)

In [114]:
print(requiredData.shape)

(44, 3)


In [115]:
dataLength = len(requiredData)

In [116]:
print(dataLength)

44


In [117]:
twoThirds = int(len(requiredData) * 2/3)

In [118]:
print(twoThirds)

29


In [119]:
trainingSet = requiredData[:twoThirds, :]

In [120]:
print(trainingSet.shape)

(29, 3)


In [121]:
print(len(trainingSet))

29


In [122]:
print(trainingSet.shape)

(29, 3)


In [123]:
testingSet = requiredData[(twoThirds):, :]

In [124]:
print(testingSet.shape)

(15, 3)


# Training Data Set Standardization
     All columns except for the last column of the training matrix are standardized

In [125]:
average_trainingSet = np.mean(trainingSet[:,:-1], axis = 0)

In [126]:
sd_trainingSet = np.std(trainingSet[:,:-1], axis = 0)

In [127]:
print(average_trainingSet)

[77.44827586 27.82758621]


In [128]:
print(sd_trainingSet)

[42.95834888  2.13459138]


In [129]:
standardized_trainingSet = (trainingSet[:,:-1] - average_trainingSet) / sd_trainingSet

In [130]:
print(standardized_trainingSet.shape)

(29, 2)


In [131]:
average_testingSet = np.mean(testingSet[:,:-1], axis = 0)

In [132]:
sd_testingSet = np.std(testingSet[:,:-1], axis = 0)

In [133]:
print(average_testingSet)

[94.26666667 28.33333333]


In [134]:
print(sd_testingSet)

[43.91274176  2.38513918]


In [135]:
standardized_testingSet = (testingSet[:,:-1] - average_testingSet) / sd_testingSet

In [136]:
print(standardized_testingSet.shape)

(15, 2)


In [137]:
y_trainingSet = trainingSet[:,-1]

In [138]:
print(y_trainingSet.shape)

(29,)


In [139]:
# now to add a column of ones to the training dataset

In [140]:
ones_column = np.ones((len(standardized_trainingSet),1), dtype=int)

In [141]:
print(ones_column.shape)


(29, 1)


In [142]:
updated_trainingSet = np.hstack((ones_column, standardized_trainingSet))

In [143]:
print(updated_trainingSet.shape)

(29, 3)


In [144]:
print(np.transpose(updated_trainingSet).shape)

(3, 29)


# Computing Weights

In [145]:
# now the task is to apply the rule of closed form linear regression using LSE
# the formula is theta = (X' * X) ^(-1) * X' * Y



In [146]:
xTx = np.matmul(updated_trainingSet.T, updated_trainingSet)

In [147]:
inverse = np.linalg.inv(xTx)

In [148]:
print(inverse)

[[ 3.44827586e-02  2.65922284e-18 -1.61538798e-18]
 [ 2.65922284e-18  3.44875186e-02 -4.05164901e-04]
 [-1.61538798e-18 -4.05164901e-04  3.44875186e-02]]


In [149]:
print(y_trainingSet.shape)

(29,)


In [150]:
xTxXt = np.matmul(inverse, updated_trainingSet.T)

In [151]:
np.matmul(xTxXt, y_trainingSet)

array([2973.44827586, 1189.56395194, -349.09155245])

In [152]:
reqd_wts = np.dot(np.linalg.inv(np.dot(updated_trainingSet.T, updated_trainingSet)), updated_trainingSet.T)

In [153]:
print(reqd_wts.shape)

(3, 29)


In [154]:
weights = np.dot(reqd_wts, y_trainingSet)

In [155]:
print(weights)

[2973.44827586 1189.56395194 -349.09155245]


In [156]:
print(standardized_testingSet)

[[ 1.33750094 -1.39754249]
 [ 1.01868687  1.11803399]
 [ 0.06224465  1.11803399]
 [-1.21301163  1.11803399]
 [ 0.6998728   0.2795085 ]
 [ 1.01868687  0.2795085 ]
 [ 1.01868687 -1.39754249]
 [-0.57538349 -1.39754249]
 [-0.89419756  1.11803399]
 [ 0.06224465  0.2795085 ]
 [-1.21301163 -0.55901699]
 [-1.82786734 -1.39754249]
 [ 1.33750094 -0.55901699]
 [-0.57538349  0.2795085 ]
 [-0.25656942  1.11803399]]


In [157]:
updated_testingSet = np.hstack ( (np.ones((len(standardized_testingSet), 1)), standardized_testingSet))

In [158]:
print(updated_testingSet.shape)

(15, 3)


In [159]:
prediction = np.dot(updated_testingSet, weights)

In [160]:
print(prediction)

[5052.36145448 3794.94523055 2657.19604936 1140.19714111 3708.41766911
 4087.66739618 4673.11172742 2776.8630921  1519.44686818 2949.91821499
 1725.64147236 1286.95345007 4759.63928886 2191.41876086 2277.9463223 ]
