In [35]:
import numpy as np
import pandas as pd
import random
import math

In [36]:
dataSet = np.genfromtxt('x06simple.csv', delimiter=',')

In [37]:
dataSet = dataSet[1:,1:]

In [38]:
# set up the number of s-folds
s_folds = 20

In [39]:
# seeding the random number generator
random.seed(0)

In [40]:
np.random.shuffle(dataSet)

In [41]:
# computing the length of each fold
fold_length = math.ceil(len(dataSet) / s_folds)

In [42]:
print(fold_length)

3


In [43]:
# initializing empty list to store the error values
errors_squared = []

In [61]:
for i in range(1, s_folds+1):
    
    header = fold_length * (i - 1) + 1
    
    tail = min(header + fold_length - 1, len(dataSet))
    # generating the testing data
    testData = dataSet[header: tail+1, :]
    # generating the training data
    trainingDataUpper = dataSet[:header, :]
    trainingDataLower = dataSet[tail+1: , :]
    trainingData = np.vstack((trainingDataUpper, trainingDataLower))
    
    xTraining = trainingData[:,:-1]
    yTraining = trainingData[:,-1]
    yTraining = np.reshape(yTraining,(len(yTraining), 1))
    
    xTesting = testData[:,:-1]
    yTesting = testData[:,-1]
    yTesting = np.reshape(yTesting,(len(yTesting), 1))
    
    # standardizing the matrices
    xMean = np.mean(xTraining, axis=0)
    xStd = np.std(xTraining, axis=0)
    
    xTraining = (xTraining-xMean) / xStd
    xTesting = (xTesting-xMean) / xStd
    
    # padding 1s to the training matrix
    trainOnes = np.ones((len(xTraining)))
    xTraining = np.column_stack((trainOnes, xTraining))
    # padding 1s to the testing matrix
    testOnes = np.ones(len(xTesting))
    xTesting = np.column_stack((testOnes, xTesting))
    
    # applying the rule
    xTx = np.dot(np.transpose(xTraining), xTraining)
    xTx_inv = np.linalg.inv(xTx)
    xTx_inv_xt = np.dot(xTx_inv, np.transpose(xTraining))
    weights = np.dot(xTx_inv_xt, yTraining)    
    
    predicted_outputs = np.matmul(xTesting,weights)
    
    
    output = np.square(yTesting-predicted_outputs)
    
    output = np.sqrt()
    
    
    
    
    


[[252.68276093]
 [  5.65115489]
 [  1.59573397]]
[[458.62118385]
 [660.01363312]
 [131.64386771]]
[[-601.03844356]
 [-299.23985377]
 [ 138.31790413]]
[[-771.10314594]
 [-638.7815012 ]
 [ 404.67477711]]
[[-277.51903434]
 [-151.81836336]
 [ 222.63465364]]
[[  -44.30772326]
 [-1102.58104507]
 [  247.10026134]]
[[  831.19935457]
 [-1553.69977947]
 [  907.3452322 ]]
[[-493.44085503]
 [-827.65984213]
 [ 189.2114239 ]]
[[1361.63410026]
 [1220.44107115]
 [ -35.47162523]]
[[ 341.24786663]
 [-360.45664381]
 [ 330.35536662]]
[[ 224.00776288]
 [-786.09468246]
 [-552.9113001 ]]
[[-206.79403839]
 [ 132.38077478]
 [ 572.12965973]]
[[-1104.74543559]
 [   96.48998176]
 [  732.83787668]]
[[ 819.42772571]
 [-444.9906127 ]
 [-758.1397375 ]]
[[59.38715993]]
[]
[]
[]
[]
[]
